# Generated by Django 4.0.1 on 2022-01-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restapi", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense",
            old_name="date_update",
            new_name="date_updated",
        ),
        migrations.RenameField(
            model_name="expense",
            old_name="descreption",
            new_name="description",
        ),
    ]
